name: Run Things on Push

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test